<?
define('LOG_FILENAME' , "/local/php_interface/log.txt");

const ID_PROPERTY_PREMIUM = 25;
const ID_PREM_STATUS_STANDART = 18;
const ID_PREM_STATUS_PREMIUM = 19;
const ID_PREM_STATUS_SUPER_PREMIUM = 20;
const ID_CATALOG = 2;
const ID_GROUP_PREMIUM_USERS = 9;
const ID_GROUP_SUPER_PREMIUM_USERS = 10;
const ID_GROUP_ALL_USERS = 2;
const PRICE_STATUS_PREMIUM_USER = 10000;
const PRICE_STATUS_SUPER_PREMIUM_USER = 30000;